export const ROUTES = [
  { id: 1, linkName: "Home", routeTo: "/" },
  { id: 2, linkName: "About Us", routeTo: "/about-us" },
  { id: 3, linkName: "Contact", routeTo: "/contact" },
  { id: 4, linkName: "Admin", routeTo: "/admin" },
];

export const homePageDummyData = [
  {
    id: 1,
    title: "What is Lorem Ipsum?",
    content:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
  },

  {
    id: 2,
    title: "Where does it come from?",
    content:
      "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of 'de Finibus Bonorum et Malorum' (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, 'Lorem ipsum dolor sit amet..', comes from a line in section 1.10.32.The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from 'de Finibus Bonorum et Malorum' by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.",
  },

  {
    id: 3,
    title: "Why do we use it?",
    content:
      "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).",
  },

  {
    id: 4,
    title: "Where can I get some?",
    content:
      "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.",
  },
];

export const aboutUsDummyData = [
  "Reprehenderit id non ad anim est sit amet ex enim et elit laboris non exercitation aliqua pariatur aliqua nisi cillum deserunt voluptate minim commodo consectetur quis sint cillum nisi occaecat aliqua esse pariatur dolor id ullamco aliquip reprehenderit occaecat nostrud enim nostrud reprehenderit sint et duis magna ullamco exercitation nisi cillum commodo aliqua mollit. Occaecat amet mollit anim incididunt dolor laboris ullamco culpa nulla anim deserunt qui Lorem et nostrud consequat nostrud ad exercitation in non elit deserunt reprehenderit est est eu laboris qui anim ut reprehenderit elit magna aute veniam magna sint nisi consequat pariatur aute ex enim ex veniam nisi consequat laborum ex tempor occaecat voluptate. Culpa veniam tempor labore proident eiusmod sunt et duis eu ipsum eu nulla ex nisi cillum aute qui cupidatat laborum velit irure occaecat eu laboris consequat minim non proident amet quis do irure commodo occaecat duis enim aliquip nisi ea ullamco proident occaecat reprehenderit occaecat proident sit adipisicing officia quis exercitation deserunt cupidatat sit consequat. Ad nulla ut deserunt duis do minim occaecat cupidatat nostrud aliqua anim adipisicing consequat esse quis nulla adipisicing excepteur do irure ad commodo deserunt cupidatat nisi cillum ad ut consequat magna culpa excepteur dolore tempor est amet deserunt sunt commodo nostrud tempor adipisicing consectetur sit non ut adipisicing sint Lorem aliqua proident laboris aliqua velit id eu magna deserunt. Excepteur veniam deserunt ullamco  ipsum do est laborum in adipisicing cillum consectetur exercitation sunt voluptate deserunt ut exercitation adipisicing nisi id consequat in nulla anim nisi nisi aute Lorem ullamco qui sint sit reprehenderit cupidatat Lorem do laboris officia quis in ad esse mollit cupidatat commodo aliqua sit pariatur et aliquip non excepteur velit cupidatat exercitation.",

  "Voluptate id aute quis do deserunt adipisicing in commodo do incididunt eiusmod anim commodo id sunt enim eu dolore in nostrud non sint minim duis qui officia eu dolor elit in excepteur quis do incididunt do dolor velit cupidatat tempor nisi dolor laborum ad aute nostrud eu exercitation esse incididunt nisi in. Occaecat duis ullamco ullamco ipsum quis excepteur id ex minim irure ut sit id sunt exercitation cupidatat nostrud incididunt esse nisi sunt consequat amet enim ullamco dolor in proident id non irure culpa irure consectetur culpa dolore anim eiusmod esse voluptate veniam dolor laborum eu veniam quis aute eu enim est est laboris. Enim elit amet commodo consequat incididunt fugiat incididunt laborum incididunt nisi excepteur ad exercitation nostrud eiusmod aute eiusmod excepteur do esse sunt nisi culpa pariatur exercitation sint ullamco culpa sit veniam dolor proident non dolor minim pariatur ex incididunt commodo culpa ex voluptate sunt qui sint sunt deserunt excepteur eiusmod et laboris ea consequat. Consectetur aliqua non proident qui pariatur ipsum eiusmod dolore amet non id anim deserunt consequat duis proident mollit labore et laborum reprehenderit deserunt do ad sunt labore aliquip laborum ea ut id magna laboris qui aliquip et amet anim dolore consectetur consectetur enim pariatur quis sint dolore labore voluptate cillum reprehenderit sint aliquip exercitation fugiat do consectetur est. Sint labore Lorem sint non adipisicing est consectetur incididunt minim cupidatat enim enim nulla nulla sit nisi reprehenderit dolore eiusmod exercitation esse ea elit excepteur anim dolor ut excepteur nostrud minim aute do labore reprehenderit irure elit adipisicing id elit magna labore sunt id occaecat ut ad et eiusmod Lorem fugiat labore culpa in id nisi consequat.",

  "Incididunt officia pariatur magna ut minim minim aute non anim ex consequat anim nulla cupidatat adipisicing quis dolore velit deserunt dolore esse sunt officia commodo cupidatat amet consequat cupidatat ea nisi consequat ipsum consequat aliquip aliquip cillum eu culpa enim elit sunt deserunt sunt est amet quis sint ipsum sunt. Tempor sint dolor veniam aliqua do dolore aute anim sint commodo ut nostrud esse exercitation duis irure ex elit enim velit pariatur in est nisi ex nulla dolor et cupidatat duis nostrud Lorem incididunt reprehenderit consectetur laboris sit reprehenderit sint voluptate nisi ex elit officia irure ad deserunt magna duis. Cillum fugiat enim sit laboris mollit nulla officia cillum consequat irure exercitation labore incididunt sit Lorem sunt ad nostrud fugiat labore adipisicing reprehenderit aute aliquip laboris pariatur cillum eu cillum velit laboris aute excepteur anim incididunt et et est sint quis qui amet minim ipsum qui culpa sint Lorem tempor aute sint aliqua consequat aliqua cupidatat. Anim ut laborum sunt reprehenderit culpa laboris excepteur incididunt laboris sint in qui nostrud sunt cillum occaecat Lorem sit minim ex nulla Lorem tempor deserunt anim enim deserunt consequat consectetur nisi reprehenderit ad fugiat enim nisi nostrud proident commodo Lorem incididunt adipisicing et veniam irure dolore ut ipsum reprehenderit excepteur quis. Enim aute duis consequat et cillum do excepteur laboris aliqua anim aliqua ut deserunt sunt aute pariatur laboris fugiat tempor deserunt ad anim ea labore labore aute officia adipisicing minim commodo cillum enim quis eiusmod veniam fugiat cillumcillum irure eu voluptate culpa in laboris Lorem sit elit nisi eu ut in.",
];
